name: Build

on:
  push:
    branches: [main]
  pull_request:

env:
  NODE_VERSION: "18.x"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"

      - name: Build package
        run: |
          npm install
          npm run build

  test:
    name: Test stan strategy
    runs-on: ubuntu-latest

    services:
      nats:
        image: nats:2-alpine
        ports:
          - 8222:8222
          - 4222:4222

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"

      - name: Run tests
        run: |
          npm install
          npm test
          npm run test:e2e
